version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16-node

    working_directory: ~/rpnow

    steps:
      - checkout

      - restore_cache:
          key: node_modules-{{ checksum "views/package.json" }}
      - restore_cache:
          key: go-pkg-mod

      - run: make

      - save_cache:
          key: node_modules-{{ checksum "views/package.json" }}
          paths:
            - ./views/node_modules
      - save_cache:
          key: go-pkg-mod
          paths:
            - /go/pkg

      - store_artifacts:
          path: rpnow-linux.tar.gz
          destination: rpnow-linux.tar.gz
      - store_artifacts:
          path: rpnow-windows.zip
          destination: rpnow-windows.zip